Document: iotivity-constrained
Title: Debian iotivity-constrained Manual
Author: <insert document author here>
Abstract: This manual describes what iotivity-constrained is
 and how it can be used to
 manage online manuals on Debian systems.
Section: unknown

Format: debiandoc-sgml
Files: /usr/share/doc/iotivity-constrained/iotivity-constrained.sgml.gz

Format: postscript
Files: /usr/share/doc/iotivity-constrained/iotivity-constrained.ps.gz

Format: text
Files: /usr/share/doc/iotivity-constrained/iotivity-constrained.text.gz

Format: HTML
Index: /usr/share/doc/iotivity-constrained/html/index.html
Files: /usr/share/doc/iotivity-constrained/html/*.html
