FROM ubuntu:22.04 AS service
RUN apt-get update && \
    DEBIAN_FRONTEND=noninteractive apt-get install -y --no-install-recommends adduser build-essential \
    ca-certificates cmake g++ gcc gcovr git python3 && \
    apt-get clean
ARG BUILD_TYPE=Debug
ARG BUILD_ARGS=
# install libfaketime
RUN git clone https://github.com/wolfcw/libfaketime.git && \
    cd /libfaketime/src && \
    make install FAKETIME_COMPILE_CFLAGS="-DFAKE_SETTIME"
WORKDIR /
RUN mkdir /device-provisioning-client
COPY . /device-provisioning-client
RUN adduser nonroot && \
    chown -R nonroot:nonroot /device-provisioning-client && \
    mkdir /dps && \
    chown nonroot:nonroot /dps
USER nonroot
WORKDIR /device-provisioning-client
RUN mkdir build && \
    cd build && \
    cmake -DCMAKE_VERBOSE_MAKEFILE=ON -DCMAKE_BUILD_TYPE=${BUILD_TYPE} -DOC_CLOUD_ENABLED=ON \
    -DOC_COLLECTIONS_IF_CREATE_ENABLED=ON -DOC_OSCORE_ENABLED=OFF -DOC_DISCOVERY_RESOURCE_OBSERVABLE_ENABLED=ON \
    -DOC_DEBUG_ENABLED=ON -DPLGD_DEV_TIME_ENABLED=ON -DPLGD_DEV_DEVICE_PROVISIONING_ENABLED=ON \
    -DPLGD_DEV_DEVICE_PROVISIONING_TEST_PROPERTIES_ENABLED=ON -DBUILD_TESTING=ON ${BUILD_ARGS} .. && \
    cmake --build . --target mbedtls mbedx509 mbedcrypto && \
    cmake --build . -j$(nproc) --target dps_cloud_server && \
    cp /device-provisioning-client/build/apps/dps_cloud_server /dps/

WORKDIR /dps
ENV LD_PRELOAD=/usr/local/lib/faketime/libfaketimeMT.so.1
ENV FAKETIME="@2011-01-01 12:00:00"
ENV FAKETIME_DONT_FAKE_MONOTONIC=1
ENV FAKETIME_TIMESTAMP_FILE=
ENV FAKETIME_UPDATE_TIMESTAMP_FILE=
ENV FAKETIME_DONT_RESET=
ENV FAKETIME_NO_CACHE=
ENV FAKETIME_CACHE_DURATION=
ENTRYPOINT [ "./dps_cloud_server" ]
