# This is a basic workflow to help you get started with Actions

name: CI building android

# Controls when the action will run.
on:
  # Triggers the workflow on push or pull request events but only for the master branch
  push:
    branches: [master]
  pull_request:
    branches: [master]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  make_android:
    # The type of runner that the job will run on
    runs-on: ubuntu-22.04
    strategy:
      fail-fast: false
      matrix:
        include:
          # default (ip4 on, secure on, pki on, dynamic allocation on, tcp on, cloud on, java on, IDD on)
          - args: ""
          # debug on
          - args: "DEBUG=1"
          # secure off
          - args: "SECURE=0"
          # dynamic allocation off
          - args: "DYNAMIC=0"
          # secure off, dynamic allocation off
          - args: "SECURE=0 DYNAMIC=0"

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE,  so your job can access it
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          submodules: "true"

      - uses: nttld/setup-ndk@v1
        id: setup-ndk
        with:
          ndk-version: r25

      # Runs a set of commands using the runners shell
      - name: build
        run: |
          # debugging info
          env
          # build android
          cd port/android
          # show which compilers there are
          # note that this is hard coded in the makefile
          ls -l  /usr/local/lib/android/sdk/ndk/
          make ${{ matrix.args }}
        env:
          ANDROID_NDK_HOME: ${{ steps.setup-ndk.outputs.ndk-path }}
          MYGITHUB_ACTIONS: true
