# This is a basic workflow to help you get started with Actions

name: CI building android

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: ${{ github.ref_name != 'master' }}

# Controls when the action will run.
on:
  push:
    branches:
      - master
  pull_request:
    types: [opened, synchronize, reopened]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  make_android:
    # The type of runner that the job will run on
    runs-on: ubuntu-22.04
    strategy:
      fail-fast: false
      matrix:
        include:
          # default (ip4 on, secure on, pki on, dynamic allocation on, tcp on, cloud on, java on, IDD on)
          - args: ""
          # debug on
          - args: "DEBUG=1"
          # secure off
          - args: "SECURE=0"
          # TODO: reenable when dynamic allocation is fixed
          # dynamic allocation off
          # - args: "DYNAMIC=0"
          # secure off, dynamic allocation off
          # - args: "SECURE=0 DYNAMIC=0"
          # android 10
          - args: "ANDROID_API=29"
          # android 11
          - args: "ANDROID_API=30"
          # android 12
          - args: "ANDROID_API=31"
          # android 13
          - args: "ANDROID_API=33"

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE,  so your job can access it
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          submodules: "true"

      - uses: nttld/setup-ndk@v1
        id: setup-ndk
        with:
          ndk-version: r25

      # Runs a set of commands using the runners shell
      - name: build
        run: |
          # debugging info
          env
          # build android
          cd port/android
          # show which compilers there are
          # note that this is hard coded in the makefile
          ls -l  /usr/local/lib/android/sdk/ndk/
          make ${{ matrix.args }}
        env:
          ANDROID_NDK_HOME: ${{ steps.setup-ndk.outputs.ndk-path }}
          MYGITHUB_ACTIONS: true
