# Build with sanitizers on Linux with CMake and execute tests

name: CI-cmake building with sanitizers on linux

on:
  # Triggers the workflow on push or pull request events but only for the master branch
  push:
    branches: [master]
  pull_request:
    branches: [master]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  cmake_linux_sanitized:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        include:
          # address sanitizer
          - args: -DOC_ASAN_ENABLED=ON
          # leak sanitizer
          - args: -DOC_LSAN_ENABLED=ON
          # thread sanitizer
          - args: -DOC_TSAN_ENABLED=ON
          # undefined behaviour sanitizer
          - args: -DOC_UBSAN_ENABLED=ON
          # TODO: update gtest
          # - args: -DOC_MSAN_ENABLED=ON

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          submodules: "true"

      - name: Sanitized build
        run: |
          mkdir linuxbuild
          cd linuxbuild
          cmake ${{ matrix.args }} -DCMAKE_BUILD_TYPE=Debug -DOC_CLOUD_ENABLED=ON -DOC_COLLECTIONS_IF_CREATE_ENABLED=ON -DOC_MNT_ENABLED=ON -DOC_SOFTWARE_UPDATE_ENABLED=ON -DOC_WKCORE_ENABLED=ON -DBUILD_TESTING=ON ../.
          make all

      - name: Test
        run: |
          cd linuxbuild
          ctest --verbose --label-regex "oc-unittest"
