name: OCF Conformance Test
on:
  push:
    branches:
      - master
    tags:
      - "*"
  pull_request:
  
jobs:
  test:
    runs-on: [self-hosted, windows, ctt]
    steps:
      - name: Get commit SHA
        id: commit
        run: |
          if ("${{github.event_name}}" -eq "pull_request") {
            echo "::set-output name=sha::${{github.event.pull_request.head.sha}}"
          } else {
            echo "::set-output name=sha::${{github.sha}}"
          }
      - name: Test
        run: python ../../github_run_ci.py --commit ${{steps.commit.outputs.sha}}
      - name: Folder content
        if: success() || failure()
        run: Get-ChildItem
      - name: Archive Test Results
        if: success() || failure()
        uses: actions/upload-artifact@v3
        with:
          name: logs
          path: results/*.octt
