name: OCF Conformance Test
on:
  pull_request:
    types:
      - opened
  push:
    branches:
      - master
    tags:
      - "*"
    issue_comment:
      types: [edited]
  
jobs:
  comment:
    if: github.event_name == 'pull_request'
    runs-on: [self-hosted, windows, ctt]
    steps:
      - name: Generate token
        id: generate_token
        uses: tibdex/github-app-token@v1
        with:
          app_id: ${{ secrets.APP_ID }}
          private_key: ${{ secrets.PRIVATE_KEY }}
          installation_id: 24124545
      - name: Create comment
        uses: peter-evans/create-or-update-comment@v1
        with:
          token: ${{ steps.generate_token.outputs.token }}
          issue-number: ${{ github.event.pull_request.number }}
          body: |
            :tada: Thank you for your code contribution! To guarantee the change/addition is conformant to the [OCF Specification](https://openconnectivity.org), we would like to ask you to execute OCF Conformance Testing of your change :point_up: **when your work is ready to be reviewed**.
            
            ---

            - [ ] <!-- ctt-trigger -->If you want to execute OCF Conformance Tests for the latest commit ${{ github.event.pull_request.head.sha }}, click this checkbox and hold on.

            --- 
  test:
    if: github.event_name == 'push' || (github.event_name == 'issue_comment' && contains(github.event.comment.body, '[x] <!-- ctt-trigger -->'))
    runs-on: [self-hosted, windows, ctt]
    steps:
      - name: Get commit SHA
        id: commit
        run: |
          if ("${{github.event_name}}" -eq "pull_request") {
            echo "::set-output name=sha::${{github.event.pull_request.head.sha}}"
          } else {
            echo "::set-output name=sha::${{github.sha}}"
          }
      - name: Generate token
        if: contains(github.event.comment.body, '[x] <!-- ctt-trigger -->')
        id: generate_token
        uses: tibdex/github-app-token@v1
        with:
          app_id: ${{ secrets.APP_ID }}
          private_key: ${{ secrets.PRIVATE_KEY }}
          installation_id: 24124545
      - name: Add reaction
        if: contains(github.event.comment.body, '[x] <!-- ctt-trigger -->')
        uses: peter-evans/create-or-update-comment@v2
        with:
          comment-id: ${{ github.event.comment.id }}
          body: |
            :tada: Thank you for your code contribution! To guarantee the change/addition is conformant to the [OCF Specification](https://openconnectivity.org), we would like to ask you to execute OCF Conformance Testing of your change :point_up: **when your work is ready to be reviewed**.
            
            ---

            :construction_worker: Test in progress!

            --- 
          edit-mode: replace
      - name: Test
        run: python ../../github_run_ci.py --commit ${{steps.commit.outputs.sha}}
      - name: Archive Test Results
        if: success() || failure()
        uses: actions/upload-artifact@v3
        with:
          name: logs
          path: results/*.octt
      - name: Add reaction
        if: (success() || failure()) && contains(github.event.comment.body, '[x] <!-- ctt-trigger -->')
        uses: peter-evans/create-or-update-comment@v2
        with:
          comment-id: ${{ github.event.comment.id }}
          body: |
            :tada: Thank you for your code contribution! To guarantee the change/addition is conformant to the [OCF Specification](https://openconnectivity.org), we would like to ask you to execute OCF Conformance Testing of your change :point_up: **when your work is ready to be reviewed**.
            
            ---

            - [ ] <!-- ctt-trigger -->If you want to execute OCF Conformance Tests for the latest commit ${{steps.commit.outputs.sha}}, click this checkbox and hold on.

            --- 
          edit-mode: replace
