name: Coverity Scan

on:
  schedule:
    - cron: "15 2 * * *" # every day at 2:15am
  workflow_dispatch:

jobs:
  coverity:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          submodules: "true"

      - name: Configure CMake
        run: cmake
            -DCMAKE_BUILD_TYPE=Debug
            -DCMAKE_VERBOSE_MAKEFILE=ON
            -DOC_CLOUD_ENABLED=ON
            -DOC_COLLECTIONS_IF_CREATE_ENABLED=ON
            -DOC_MNT_ENABLED=ON
            -DOC_WKCORE_ENABLED=ON
            -DOC_SOFTWARE_UPDATE_ENABLED=ON
            -DOC_PUSH_ENABLED=ON
            -DOC_DISCOVERY_RESOURCE_OBSERVABLE_ENABLED=ON
            -DOC_RESOURCE_ACCESS_IN_RFOTM_ENABLED=ON
            -DPLGD_DEV_TIME_ENABLED=ON
            -DOC_ETAG_ENABLED=ON
            -DOC_JSON_ENCODER_ENABLED=ON
            -B ${{github.workspace}}/build

      - uses: vapier/coverity-scan-action@v1
        with:
          email: ${{ secrets.COVERITY_SCAN_EMAIL }}
          token: ${{ secrets.COVERITY_SCAN_TOKEN }}
          command: cmake --build ${{github.workspace}}/build
