name: OCF Conformance
on:
  pull_request:
    types:
      - labeled
  push:
    branches:
      - master
      - main
    tags:
      - "*"
jobs:
  test:
    name: Test
    runs-on: [self-hosted, windows, ctt]
    steps:
      - name: Get commit SHA
        id: commit
        run: |
          if ("${{github.event_name}}" -eq "pull_request") {
            echo "sha=${{github.event.pull_request.head.sha}}" >> $env:GITHUB_OUTPUT
          } else {
            echo "sha=${{github.sha}}" >> $env:GITHUB_OUTPUT
          }

      - name: Test
        run: python ../../github_run_ci.py --commit ${{steps.commit.outputs.sha}}

      - name: Archive results
        if: success() || failure()
        uses: actions/upload-artifact@v3
        with:
          name: logs
          path: results/*.octt
