name: OCF Conformance Bot
on:
  pull_request:
    types:
      - synchronize
      - opened
jobs:
  info-comment:
    name: Info comment
    if: github.event.action == 'opened'
    runs-on: ubuntu-latest
    steps:
      - name: Generate token
        id: generate_token
        uses: tibdex/github-app-token@v1
        with:
          app_id: ${{ secrets.APP_ID }}
          private_key: ${{ secrets.PRIVATE_KEY }}
          installation_id: 24124545
      - name: Publish comment
        uses: peter-evans/create-or-update-comment@v3
        with:
          token: ${{ steps.generate_token.outputs.token }}
          issue-number: ${{ github.event.pull_request.number }}
          body: |
            :tada: Thank you for your code contribution! To guarantee the change/addition is conformant to the [OCF Specification](https://openconnectivity.org), we would like to ask you to execute OCF Conformance Testing of your change :point_up: **when your work is ready to be reviewed**.

            ---

            :information_source: To verify your latest change (${{ github.event.pull_request.head.sha }}), label this PR with `OCF Conformance Testing`.

            :warning: Label is removed with every code change.
  remove-label:
    name: Remove label
    if: github.event.action == 'synchronize'
    runs-on: ubuntu-latest
    steps:
      - name: Generate token
        id: generate_token
        uses: tibdex/github-app-token@v1
        with:
          app_id: ${{ secrets.APP_ID }}
          private_key: ${{ secrets.PRIVATE_KEY }}
          installation_id: 24124545
      - name: Remove label
        uses: mondeja/remove-labels-gh-action@v1
        with:
          token: ${{ steps.generate_token.outputs.token }}
          labels: |
            OCF Conformance Testing
