name: Check ghcr images

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: ${{ github.ref_name != 'master' }}

on:
  workflow_dispatch:
    inputs:
      package:
        description: "Package to build"
        required: true
        type: choice
        options:
          - cloud-server
          - cloud-server-debug
          - cloud-server-discovery-resource-observable
          - cloud-server-discovery-resource-observable-debug
jobs:
    check_package:
      name: Check released packages
      runs-on: ubuntu-latest
      steps:
        - uses: actions/checkout@v4

        - name: Check package
          working-directory: tools
          run: |
            PACKAGE="${{ inputs.package }}" ./check_releases.sh
