name: Delete old ghcr images
on:
  schedule:
    - cron: "15 1 * * *" # every day at 1:15am
  pull_request:
    types: [closed]
  workflow_dispatch:

jobs:
  pull-request-ghcr-cleanup:
    if: ${{ github.event_name == 'pull_request' }}
    name: Delete images related to closed PR
    runs-on: ubuntu-latest
    steps:
      - name: Delete images related to closed PR
        uses: snok/container-retention-policy@v2
        with:
          image-names: cloud-server*, iotivity-lite*
          cut-off: now UTC
          account-type: org
          org-name: iotivity
          filter-tags: vnext-pr${{ github.event.pull_request.number }}*
          token: ${{ secrets.GHCR_CLEANUP_PAT }}
  nightly-ghcr-cleanup:
    # if: ${{ github.event_name == 'schedule' || github.event_name == 'workflow_dispatch' }}
    name: Delete old images
    runs-on: ubuntu-latest
    steps:
      - name: Delete older than a month vnext images
        uses: snok/container-retention-policy@v2
        with:
          image-names: cloud-server*, iotivity-lite*
          cut-off: One month ago UTC
          account-type: org
          org-name: iotivity
          filter-tags: vnext-*
          skip-tags: vnext-pr*, master
          token: ${{ secrets.GHCR_CLEANUP_PAT }}
      # Cannot enable clean-up of untagged images until issue#63 is fixed
      # https://github.com/snok/container-retention-policy/issues/63
      # - name: Delete untagged images older than a month
      #   uses: snok/container-retention-policy@v2
      #   with:
      #     image-names: cloud-server*, iotivity-lite*
      #     cut-off: One month ago UTC
      #     account-type: org
      #     org-name: iotivity
      #     untagged-only: true
      #     token: ${{ secrets.GHCR_CLEANUP_PAT }}
