# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.

name: Run plgd/device test with cloud_server and a single configuration

on:
  workflow_call:
    inputs:
      build_args:
        description: build arguments forwarded to CMake in docker/apps/Dockerfile.cloud-server-debug
        type: string
        required: true
      build_type:
        type: string
        required: true
      cert_signature_algorithm:
        description: Signature algorithm used in generated certificates
        type: string
        required: false
        default: ECDSA-SHA256
      cert_elliptic_curve:
        description: Elliptic curve used to generate keys in certificates
        type: string
        required: false
        default: P256
      coverage:
        type: boolean
        required: false
        default: false
      name:
        type: string
        required: true
      skip:
        description: Skip this run of the job
        type: boolean
        required: false
        default: false
      docker_file:
        description: Dockerfile used to build the cloud server image
        type: string
        required: false
        default: docker/apps/Dockerfile.cloud-server-debug
env:
  TEST_CLOUD_SERVER_IMAGE: ghcr.io/plgd-dev/device/test-cloud-server:latest
  CERT_TOOL_IMAGE: ghcr.io/plgd-dev/hub/cert-tool:vnext
  CERT_PATH: .tmp/pki_certs
  CLOUD_SERVER_DOCKER_TAG: dbg

jobs:
  plgd-device-test-with-cfg:
    if: ${{ !inputs.skip }}
    runs-on: ubuntu-22.04

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          submodules: "true"

      - name: Build cloud server docker image
        uses: docker/build-push-action@v4
        with:
          context: .
          push: false
          file: ${{ inputs.docker_file }}
          tags: ${{ env.CLOUD_SERVER_DOCKER_TAG }}
          build-args: |
            BUILD_ARGS=${{ inputs.build_args }}
            BUILD_TYPE=${{ inputs.build_type }}

      - name: Pull plgd device tests image
        run: docker pull ${{ env.TEST_CLOUD_SERVER_IMAGE }}

      - name: Setup environment
        run: |
          mkdir -p "$(pwd)/${{ env.CERT_PATH }}"
          chmod 0777 "$(pwd)/${{ env.CERT_PATH }}"
          docker pull ${{ env.CERT_TOOL_IMAGE }}
          docker run --rm -v `pwd`/${{ env.CERT_PATH }}:/out ${{ env.CERT_TOOL_IMAGE }} --outCert=/out/cloudca.pem \
            --outKey=/out/cloudcakey.pem --cert.subject.cn="ca" --cert.signatureAlgorithm="${{ inputs.cert_signature_algorithm }}" \
            --cert.ellipticCurve="${{ inputs.cert_elliptic_curve }}" --cmd.generateRootCA
          docker run --rm -v `pwd`/${{ env.CERT_PATH }}:/out ${{ env.CERT_TOOL_IMAGE }} --signerCert=/out/cloudca.pem \
            --signerKey=/out/cloudcakey.pem  --outCert=/out/intermediatecacrt.pem --outKey=/out/intermediatecakey.pem \
            --cert.basicConstraints.maxPathLen=0 --cert.subject.cn="intermediateCA" \
            --cert.signatureAlgorithm="${{ inputs.cert_signature_algorithm }}" --cert.ellipticCurve="${{ inputs.cert_elliptic_curve }}" \
            --cmd.generateIntermediateCA
          docker run --rm -v `pwd`/${{ env.CERT_PATH }}:/out ${{ env.CERT_TOOL_IMAGE }} --signerCert=/out/intermediatecacrt.pem \
            --signerKey=/out/intermediatecakey.pem --outCert=/out/mfgcrt.pem --outKey=/out/mfgkey.pem --cert.san.domain=localhost \
            --cert.san.ip=127.0.0.1 --cert.subject.cn="mfg" --cert.signatureAlgorithm="${{ inputs.cert_signature_algorithm }}" \
            --cert.ellipticCurve="${{ inputs.cert_elliptic_curve }}" --cmd.generateCertificate
          sudo chown -R $(whoami) "$(pwd)/${{ env.CERT_PATH }}"
          chmod -R 0777 "$(pwd)/${{ env.CERT_PATH }}"

      - name: Run cloud server container
        run: |
          docker run --privileged -d --network=host -v `pwd`/${{ env.CERT_PATH }}:/pki_certs -v `pwd`/data:/tmp \
            -v `pwd`/data/coverage:/data/coverage --name ${{ inputs.name }} ${{ env.CLOUD_SERVER_DOCKER_TAG }} devsim-`hostname`

      - name: Run plgd device tests image
        run: |
          docker run --rm --network=host -v `pwd`/${{ env.CERT_PATH }}:/pki_certs ${{ env.TEST_CLOUD_SERVER_IMAGE }} \
            -test.parallel 1 -test.v

      - name: Get output file name
        if: ${{ inputs.coverage }}
        id: coverage
        run: |
          SUFFIX=`echo "-DCMAKE_BUILD_TYPE=${{ inputs.build_type }} ${{ inputs.build_args }} ${{ inputs.name }} -DBUILD_TESTING=ON" | sha1sum | cut -f 1 -d ' '`
          echo "filename=coverage-plgd-device-${SUFFIX}.json" >> $GITHUB_OUTPUT

      - name: Gather coverage data
        if: ${{ inputs.coverage }}
        run: |
          # stop to generate .gcda files
          docker stop --time 60 ${{ inputs.name }}
          # restart to generate report from the .gcda files
          docker start ${{ inputs.name }}
          # see Dockerfile.cloud-server-debug for the absolute path with the iotivity-lite checkout
          docker exec --workdir "/iotivity-lite/tools" ${{ inputs.name }} /bin/bash -c "./collect-coverage.sh \
            --output /data/coverage/${{ steps.coverage.outputs.filename }}"

      - name: Upload coverage data
        if: ${{ inputs.coverage }}
        uses: actions/upload-artifact@v3
        with:
          name: plgd-device-coverage
          path: data/coverage/${{ steps.coverage.outputs.filename }}
          if-no-files-found: error
          retention-days: 1

      - name: Remove cloud server container
        if: ${{ always() }}
        run: |
          # enough time for sanitized build to generate report on exit
          docker stop --time 300 ${{ inputs.name }} || :
          docker rm -f ${{ inputs.name }} || :

      - name: Collect cloud server logs when the test fails
        if: ${{ failure() }}
        run: cat `pwd`/data/0.log

      - name: Collect sanitizers cloud server logs
        if: ${{ always() }}
        run: |
          if ls `pwd`/data/0.asan.log* 1> /dev/null 2>&1; then \
            sudo cat `pwd`/data/0.asan.log*; \
          fi
          if ls `pwd`/data/0.tsan.log* 1> /dev/null 2>&1; then \
            sudo cat `pwd`/data/0.tsan.log*; \
          fi
